#List latches involved in latch waits and their wait time
#TOTAL_EXTENDED_LATCH_WAIT_TIME is in milliseconds

SELECT SUBSTR(LATCH_NAME,1,100) AS LATCH_NAME,TOTAL_EXTENDED_LATCH_WAITS,TOTAL_EXTENDED_LATCH_WAIT_TIME FROM TABLE(MON_GET_EXTENDED_LATCH_WAIT(NULL))

#Order top 20 by TOTAL_EXTENDED_LATCH_WAIT_TIME 
SELECT SUBSTR(LATCH_NAME,1,100) AS LATCH_NAME,TOTAL_EXTENDED_LATCH_WAITS,TOTAL_EXTENDED_LATCH_WAIT_TIME FROM TABLE(MON_GET_EXTENDED_LATCH_WAIT(NULL)) ORDER BY TOTAL_EXTENDED_LATCH_WAIT_TIME DESC FETCH FIRST 20 ROWS ONLY

#Order top 20 by TOTAL_EXTENDED_LATCH_WAITS 
SELECT SUBSTR(LATCH_NAME,1,100) AS LATCH_NAME,TOTAL_EXTENDED_LATCH_WAITS,TOTAL_EXTENDED_LATCH_WAIT_TIME FROM TABLE(MON_GET_EXTENDED_LATCH_WAIT(NULL)) ORDER BY TOTAL_EXTENDED_LATCH_WAITS DESC FETCH FIRST 20 ROWS ONLY
